@startuml 例題2-6
actor 人事担当者
actor 社員
rectangle 従業員登録システム {
  usecase 従業員情報登録
  usecase 従業員情報参照
  usecase 従業員情報変更申請
  usecase 従業員情報修正
  人事担当者 --> 従業員情報登録
  社員 --> 従業員情報参照
  社員 --> 従業員情報変更申請
  人事担当者 --> 従業員情報修正
}
@enduml