@startuml 演習6-5ユースケース図
actor ユーザー
rectangle ライントレーサー {
  (システムを起動する)
  (システムを停止する)
}
actor 光センサー
ユーザー --> (ライントレーサーを操作する)
(ライントレーサーを操作する) --> (システムを起動する)
(ライントレーサーを操作する) --> (システムを停止する)
光センサー --> (ライン上にある)
(ライン上にある) --> (右旋回を開始する)
(ライン上にある) --> (左旋回を開始する)
(右旋回を開始する) --> (ラインの右境界線上を進む)
(左旋回を開始する) --> (ラインの右境界線上を進む)
ライントレーサー --> 光センサー
ライントレーサー --> (右モータOFF)
ライントレーサー --> (左モータON)
ライントレーサー --> (右モータON)
ライントレーサー --> (左モータOFF)
ライントレーサー --> (電源SWをON)
ライントレーサー --> (電源SWをOFF)
@enduml