@startuml 演習3-2
class 医師 {
    -名前
    -所属医局
    +診察する(患者)
}
class 患者 {
    -名前
    -担当医
}
class 診察記録 {
    -診察日時
    -患者
    -医師
    -診察結果
}
class 医局 {
    -名前 : 文字列
}
医師 --> 医局
患者 --> 医師
診察記録 --> 患者
診察記録 --> 医師
@enduml