@startuml 演習3-3
class ホテル {
   -部屋
   +利用可能な部屋を検索()
}
class 部屋 {
  -タイプ
  -価格
  -キャンペーン価格
  +部屋を予約()
}
class 予約 {
  -チェックイン
  -滞在期間
  -値段
}
class 利用者 {
  -名前
  -住所
  -電話番号
  +部屋を予約()
}
ホテル -> 部屋
部屋 -> 予約
利用者 -> 部屋
@enduml