@startuml 演習4-5
title 商品情報を検索するシーケンス図
actor 会員
boundary 商品検索画面
control 商品検索コントローラ
control 商品情報検索クラス
entity 商品情報
会員 -> 商品検索画面: 商品検索を開く
activate 商品検索画面
商品検索画面 -> 商品検索コントローラ: 商品検索を要求する
activate 商品検索コントローラ
商品検索コントローラ -> 商品情報検索クラス: 商品情報を検索する
activate 商品情報検索クラス
商品情報検索クラス -> 商品情報: 商品情報を取得する
activate 商品情報
商品情報検索クラス -> 商品検索コントローラ: 商品情報を返す
deactivate 商品情報
商品検索コントローラ -> 商品検索画面: 商品情報を表示する
deactivate 商品検索コントローラ
@enduml