@startuml 演習7-4-1
class ドリンク {
    +種別
}
class フード {
    +種別
}
class 商品 {
    +名称
    +単価
}
class 注文明細 {
    +小計
    +数量
}
class 注文 {
    +合計
}
class カップ {
    +サイズ
}
class 材料 {
    +名前
}
class ハンバーガー {
    +材料[]
}
class 割引クーポン {
    +値引額
    +期限
}
ドリンク --> カップ
フード --> ハンバーガー
フード --> ポテト
商品 <|-- ドリンク
商品 <|-- フード
注文明細 "1" *-- "1" 商品
注文 "1" *-- "*" 注文明細
割引クーポン -- 注文
ポテト --> フード
パン --> ハンバーガー
肉 --> ハンバーガー
野菜 --> ハンバーガー
チーズ --> ハンバーガー
@enduml