@startuml 演習6-3ステートマシン図
state メニュー
[*] -> メニュー
メニュー  -> [*]
メニュー --> 予約と確認 : 名前と電話番号を入力して、登録ボタンを押す
予約と確認 -right-> あなたの順番 : 現在の登録者番号の次に、名前、電話番号、が記録される
予約と確認 -right-> あなたの順番 : 名前か電話番号を入力してから確認ボタンを押す
予約と確認 --> メニュー : 名前か電話番号を入力してから取消ボタンを押す
メニュー <-- あなたの順番 : あなたの登録者番号を表示する
メニュー --> 今の順番 : 診察中の患者の順番を表示する
メニュー <-right- 今の順番 : 看護士が現在の患者番号を一つ増やす
@enduml