@startuml 演習3-7
title 顧客注文管理システム
class 顧客 {
  +名前
  +注文する(注文)
}
abstract class 商品 {
  +型式
  +値段
}
class テレビ {
  +型式: V12345
  +値段: 100,000円
}
class 冷蔵庫 {
  +型式: R8765
  +値段: 80,000円
}
class プロジェクタ {
  +型式: P1122
  +値段: 200,000円
}
class 売り場 {
  -注文リスト: List<注文>
  +注文する(注文)
  ..注文リストとの関連..
  +get注文リスト(): List<注文>
}
class 注文 {
  -注文日時
  -商品
  -数量
  +get注文日時(): Date
  +get商品(): 商品
  +get数量(): int
}
顧客 -> 注文
注文 -> 商品
売り場 -> 注文
顧客 -> 売り場: 注文する(注文{商品=テレビ, 数量=2})
顧客 -> 売り場: 注文する(注文{商品=冷蔵庫, 数量=1})
顧客 -> 売り場: 注文する(注文{商品=冷蔵庫, 数量=1})
@enduml