@startuml 演習6-5ステートマシン図
left to right direction
[*] -> 電源SW_OFF
電源SW_OFF -> [*]
[*] -> 初期状態
初期状態 -> 電源SW_ON : 電源SWをONにする
右旋回 --> 左旋回 : 光センサーがラインを外れる
左旋回 --> 右旋回 : 光センサーが黒いライン上にある
右旋回 --> [*] : 電源SWをOFFにする
左旋回 --> [*] : 電源SWをOFFにする
@enduml