@startuml 演習7-1
|ユーザ|
start
:ユーザ名を入力する;
:パスワードを入力する;
|ユーザ|
|システム|
if (認証が成功するか？) then (成功)
else (失敗)
    while (認証が成功するか？) is (失敗)
    |ユーザ|
        :ユーザ名とパスワードを再入力する;
        :ユーザ名を入力する;
        :パスワードを入力する;
    |ユーザ|
     endwhile
endif
|システム|
|ユーザ|
:予約を行う;
:予約内容を入力する;
:予約を確定する;
:支払いを行う;
|ユーザ|
|システム|
:予約完了;
|システム|
stop
@enduml