@startuml 演習3-6
class 情報処理技術者試験 {
    -合格日: 2020/10/21
}
class LinuC試験Level1 {
    -合格日: 2021/03/28
}
class 申請者 {
    -氏名: 高橋洋平
    -試験: 情報処理技術者試験
    -LinuC試験: LinuC試験Level1
}
class 樋口正之 {
    -試験: 情報処理技術者試験
}
情報処理技術者試験 -> 申請者
情報処理技術者試験 -> 樋口正之
LinuC試験Level1 -> 申請者
@enduml