@startuml 演習6-5クラス図
class ライントレーサー {
  - 光センサー: Sensor
  - 右モータ: Motor
  - 左モータ: Motor
  - CPU: CPU
  - 電源SW: Switch
  + 電源ON()
  + 電源OFF()
}
class 光センサー {
  + 暗い(): boolean
  + 明るい(): boolean
}
class モータ {
  + ON()
  + OFF()
}
class 右モータ {
}
class 左モータ {
}
class CPU {
}
class 電源SW {
  + 入れる()
  + 切る()
}
ライントレーサー "1" *-- "1" 光センサー
ライントレーサー "1" *-- "1" 右モータ
ライントレーサー "1" *-- "1" 左モータ
ライントレーサー "1" *-- "1" CPU
ライントレーサー "1" *-- "1" 電源SW
@enduml